# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 862318eb5b71978d5b672557b251679e805f9919f4c3081a497fa8c79e95f9182a1f8eec6e9da8c3f9cb39ade1938a8f8da2fb9b174d2181253eb9c07701378a

test:
  secret_key_base: 6b295f055d480389790c9aa23521bc023b98717c98104e3947eabff1d91804888f458db0d327207881b56eda35af9b834154e92d3dd95e0c9ad2cc3cf1ed0ca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
